services:
  api:
    build: .
    image: branya/ai_code_reviewer:1.0.0
    container_name: api
    command: ["uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    restart: always
